### PR TITLE
Issue #28: All resources in the sepsis API should have a last_modified

### PR DESCRIPTION
**Pull request by sztamas**
@aahunter added last_modified to all the models in sepsis.
That was enough for the fields to show up in the API as well, because there were no customised serializers that prevents that.

``Projects`` and ``bpa_ids`` are common models not defined in sepsis, so I didn't add the last_modified field to those.
I think that's ok, but let me know if you want last_modified on those models as well.

### CODE REVIEW

**Comment by sztamas** [comment]
@grahame Could you please review?
Thanks

**Comment by sztamas** [comment]
@grahame @aahunter 

I've just noticed an issue.

All the last_modified fields I've added look like this:

`field=models.DateTimeField(default=datetime.datetime(2016, 8, 25, 14, 4, 7, 555198, tzinfo=utc), auto_now=True), preserve_default=False,),`

The default is set to 2016-08-25. The default is needed to be set for the data that is already there.
I don't really like that value, but we could:

1. allow the last_modified field to be nullable
2. keep it as not nullable but set the date to a date that has some significance. This could be something that is obviously a default like '2000-01-01'.

Which one we prefer?
I think I would go with 1. The field will be nullable, but for new rows, updates from now on it wouldn't matter because auto_now will always set the value.

**Comment by aahunter** [comment]
Personally I think that allowing last_modified to default to now() is ok. It is meant to indicate the last time the models was modified - and you could certainly making the argument that adding the field is a modification.

The field is not meant to be interpreted for an any other purpose (upload date etc). So I don't see it as an issue.

**Comment by grahame** [comment]
I agree with @aahunter's comments, and the patch otherwise looks good to me.

**Pull request merged**
